image: alpine:3.14.3

variable :
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python -V
  - apk add --update docker openrc
  - apk rc-update add docker boot 
  - pip install doit pytest requests 

test_local:
  script:
    - doit pruebas 

test_docker:
  script:
    - docker run -v `pwd`:/app/test soyjorgeprg/macime:latest


