name: Publicar imagen en DockerHub

on:
  push:
    paths:
      - "macime/*"
      - "tests/*"
      - "Dockerfile"
  tags:
    - v*

jobs:
  push_to_registry:
    name: Flujo de subida a DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Hacer checkout del repositorio
        uses: actions/checkout@v2

      - name: Log in en DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extraer metadatos para Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: soyjorgeprg/macime

      - name: Construir y subir la imagen a DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: soyjorgeprg/macime:latest
          labels: ${{ steps.meta.outputs.labels }}
