name: Publicar imagen en GCR

on:
  push:
    paths:
      - "macime/*"
      - "tests/*"
      - "Dockerfile"
    tags:
      - v*

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer checkout del repositorio
        uses: actions/checkout@v2

      - name: Log in en GCR
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GCR_TOKEN }}

      - name: Extraer metadatos para GCR
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          #Se añade la etiqueta latest (Para evitar que ponga main)
          tags: latest
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Construir y subir la imagen a DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/soyjorgeprg/macime:latest
          labels: ${{ steps.meta.outputs.labels }}
