name: Lint python
on:
  push:
    paths:
      - "**/*.py"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Hacer checkout del repositorio
        uses: actions/checkout@v2

      - name: Establecer version de Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Instalar dependencias
        run: |
          pip install doit pytest requests
    
      - name: Ejecutar linter
        run: |
          doit lint


